spring:
  application:
    name: monitoreo

# Configuración de la base de datos PostgreSQL
datasource:
  url: jdbc:postgresql://localhost:5432/monitoreo_db
  username: postgres
  password: postgres
  driver-class-name: org.postgresql.Driver

# Configuración de JPA/Hibernate
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
      jdbc:
        batch_size: 20
      order_inserts: true
      order_updates: true
  open-in-view: false

# Configuración de Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops,beans,mappings,loggers,auditevents,httptrace,scheduledtasks,threaddump,heapdump
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: development
  info:
    env:
      enabled: true
    git:
      mode: full
    build:
      enabled: true

# Configuración de logging
logging:
  level:
    com.monitoreo: DEBUG
    org.springframework.boot.actuate: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Configuración del servidor
server:
  port: 8080
  servlet:
    context-path: / 

# Configuración de Eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ofertaya_monitoreo_app
    prefer-ip-address: true 