groups:
  - name: monitoreo_alerts
    rules:
      - alert: ServicioCaido
        expr: up{job="monitoreo"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "El microservicio de monitoreo está caído"
          description: "No se detecta el servicio en el endpoint /actuator/health"

      - alert: Errores5xxElevados
        expr: rate(http_server_requests_seconds_count{outcome="SERVER_ERROR",job="monitoreo"}[1m]) > 5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Errores 5xx elevados"
          description: "Se detectan más de 5 errores 5xx por minuto en el microservicio de monitoreo"

      - alert: LatenciaElevada
        expr: histogram_quantile(0.95, sum(rate(monitoreo_eventos_creacion_tiempo_seconds_bucket{job="monitoreo"}[5m])) by (le)) > 0.3
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Latencia elevada en creación de eventos"
          description: "El 95% de las peticiones de creación de eventos supera los 300ms" 