global:
  scrape_interval: 30s  # Intervalo más largo para staging
  evaluation_interval: 30s

rule_files:
  - "alert_rules-staging.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager-staging:9093']

scrape_configs:
  - job_name: 'prometheus-staging'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'monitoreo-staging'
    static_configs:
      - targets: ['monitoreo-staging:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s  # Intervalo más largo para staging
    scrape_timeout: 10s
    honor_labels: true
    scheme: http
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_service_name]
        target_label: service 