global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  - "alert_rules.yml"

scrape_configs:
  # Prometheus se scrapea a sí mismo
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Microservicio de Monitoreo
  - job_name: 'monitoreo'
    static_configs:
      - targets: ['monitoreo:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    scheme: http
    
    # Configuración de relabeling para agregar etiquetas
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_service_name]
        target_label: service

  # Métricas del sistema (opcional)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

# Configuración de alertas (opcional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Configuración de reglas de alertas (opcional)
# rule_files:
#   - "alert_rules.yml" 