server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: monitoreo-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: monitoreo
          __path__: /var/log/monitoreo/*.log
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*.log 